# Use an official Python runtime as a parent image
FROM python:3.10

RUN apt-get -y update && apt-get -y install sqlite3

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install NLTK and download necessary resources
RUN apt-get update && apt-get install -y \
    && pip install nltk

# Install any needed dependencies specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

RUN python -m nltk.downloader punkt stopwords

# Make port 5000 available to the world outside this container
EXPOSE 80

# Run app.py when the container launches
CMD ["python", "main.py"]



contoh payload
/predict
payload
{skill:[....]}

response
{
                "status": "success",
                "method": "skill",
                "recommendations": recommendations
            }